services:
  database:
    container_name: swip-sap-database-1
    image: postgres:latest
    environment:
      - POSTGRES_USER=swip-sap
      - POSTGRES_PASSWORD=swip-sap
      - POSTGRES_DB=swip-sap

  frontend:
    container_name: swip-sap-frontend
    build: ./frontend
    ports:
      - '80:80'
